### ISSUE TITLE
I think Botania's Corporea System might allow free extractions?

### ISSUE THREAD

**Issue by Azutte** [gigaherz/Ender-Rift#2] opened 2015-08-18 21:04 UTC
Or maybe it doesn't update WAILA's RF display correctly? Or maybe I can't remember numbers over the span of a few seconds and I'm just mistaken?

I set it up with a corporea spark atop the ender rift's core, a corporea funnel over that, 
![2015-08-17_03 01 34](https://cloud.githubusercontent.com/assets/6581284/9342507/ec60bd68-45b0-11e5-8745-ffd4209bace0.png)
 
(I removed the RF production before testing this)

...a corporea spark over a nearby barrel, redstone block in an item frame on the funnel, button on the funnel...

![2015-08-17_03 04 32](https://cloud.githubusercontent.com/assets/6581284/9342543/39e189be-45b1-11e5-9f7c-b83854441c29.png)

...index and master spark nearby, second funnel-spark-frame-button setup atop the barrel (you can place blocks inside corporea sparks and it's fine), and a few stacks of redstone blocks in the barrel. Press the button on the funnel atop the rift, it transfers a stack of redstone blocks (rotate item in frame three times to make it draw 64 items) from the barrel into the ender rift. Drains RF. Press the funnel button atop the barrel, it draws a stack out of the rift into the barrel and doesn't drain RF.

**Comment by gigaherz** [comment] 2015-08-21 01:10
Sorry for the delay, there was a spammy comment discussion elsewhere and I apparently ignored more github emails than I should ;P

Hmm this made me realize something about the extraction that I didn't consider. I think the extraction is completely broken, regardless of the method used to extract.

While there's a way to tell nearby "inserters" that the block can't take an item, there's no way to tell neighbours that an item can't be extracted, without using ISidedInventory.

The problem is that ISidedInventory has to return an ARRAY with ALL THE SLOTS currently in the block and accessible by each side (which, in my case, means all of them), and in the worst case, there could be 10 million slots in the block :/

I guess I will have to implement ISidedInventory, and keep the array cached (reuse it until the slot count changes, then generate a new one).

**Comment by gigaherz** [comment] 2016-01-23 15:34
The versions for 1.8.9 don't have this issue anymore, so I will be closing this.

**Closed by gigaherz** 2016-01-23 15:34 UTC
