### ISSUE TITLE
Few bugs with testing 

### ISSUE THREAD

**Issue by Akitori** [gigaherz/Ender-Rift#33] opened 2017-08-03 15:23 UTC
Unable to pull out items using left click, also using a interface and shift clicking gives me more items than i put in, say with coal or iron ore.

**Comment by gigaherz** [comment] 2017-08-05 08:53
Hmm I didn't even remember that was a thing... I looked at the code and apparently you have to have an existing stack of the item you want (at least one item) to get more of that thing... I got 1x ender pearl in my hand, clicked, and got a stack of them from inside the rift, so it works "as intended" I guess... I really don't remember writing that code. XD

As for the interface.. it is most definitely bugged.

**Comment by gigaherz** [comment] 2017-08-12 18:00
It should hopefully be fixed in 2.1.8, but I haven't really found any way to reproduce properly, so I can't be certain. Feel free to comment here and I will reopen if it still happens.

**Closed by gigaherz** 2017-08-12 18:00 UTC
